[package]
name = "faasm-sys"
description = "Rust bindings for Faasm."
authors = ["Mayeul Fournial <mfournial@outlook.com>"]
readme = "README.md"
repository = "https://github.com/mfournial/faasm-sys"
version = "0.0.12" # in sync with Faasm
build = "build.rs"
edition = "2021"
license = "Apache-2.0"

[badges]
maintenance = { status = "experimental" }
travis-ci = { repository = "mfournial/faasm-sys" }

[[example]]
name = "hello_world"

[dependencies]

[build-dependencies]
flate2 = "1.0"
reqwest = { version = "0.11", features = ["blocking", "default-tls"], default-features = false }
tar = "0.4"

[package.metadata.docs.rs]
targets = [] # Do not build docs since this is a sys crate

